# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Catchment_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatchmentDialogBase(object):
    def setupUi(self, CatchmentDialogBase):
        CatchmentDialogBase.setObjectName("CatchmentDialogBase")
        CatchmentDialogBase.resize(484, 241)
        CatchmentDialogBase.setMouseTracking(False)
        self.txtOutput = QtWidgets.QLineEdit(CatchmentDialogBase)
        self.txtOutput.setGeometry(QtCore.QRect(170, 160, 241, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.label = QtWidgets.QLabel(CatchmentDialogBase)
        self.label.setGeometry(QtCore.QRect(93, 15, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CatchmentDialogBase)
        self.label_2.setGeometry(QtCore.QRect(64, 48, 121, 16))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.btnOpenDialog = QtWidgets.QPushButton(CatchmentDialogBase)
        self.btnOpenDialog.setGeometry(QtCore.QRect(420, 160, 51, 23))
        self.btnOpenDialog.setObjectName("btnOpenDialog")
        self.cmbLayers = QtWidgets.QComboBox(CatchmentDialogBase)
        self.cmbLayers.setGeometry(QtCore.QRect(170, 10, 301, 22))
        self.cmbLayers.setObjectName("cmbLayers")
        self.btnCancel = QtWidgets.QPushButton(CatchmentDialogBase)
        self.btnCancel.setGeometry(QtCore.QRect(396, 200, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(CatchmentDialogBase)
        self.btnOK.setGeometry(QtCore.QRect(306, 200, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.cmbFDLayer = QtWidgets.QComboBox(CatchmentDialogBase)
        self.cmbFDLayer.setGeometry(QtCore.QRect(170, 48, 301, 22))
        self.cmbFDLayer.setObjectName("cmbFDLayer")
        self.cmbFALayer = QtWidgets.QComboBox(CatchmentDialogBase)
        self.cmbFALayer.setGeometry(QtCore.QRect(170, 87, 301, 21))
        self.cmbFALayer.setObjectName("cmbFALayer")
        self.label_3 = QtWidgets.QLabel(CatchmentDialogBase)
        self.label_3.setGeometry(QtCore.QRect(36, 86, 151, 16))
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.cmbSGLayer = QtWidgets.QComboBox(CatchmentDialogBase)
        self.cmbSGLayer.setGeometry(QtCore.QRect(170, 123, 301, 22))
        self.cmbSGLayer.setObjectName("cmbSGLayer")
        self.label_4 = QtWidgets.QLabel(CatchmentDialogBase)
        self.label_4.setGeometry(QtCore.QRect(102, 123, 81, 16))
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CatchmentDialogBase)
        self.label_5.setGeometry(QtCore.QRect(106, 161, 81, 16))
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(CatchmentDialogBase)
        QtCore.QMetaObject.connectSlotsByName(CatchmentDialogBase)

    def retranslateUi(self, CatchmentDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CatchmentDialogBase.setWindowTitle(_translate("CatchmentDialogBase", "Catchment GRID Delination"))
        self.label.setText(_translate("CatchmentDialogBase", "Elevation :"))
        self.label_2.setText(_translate("CatchmentDialogBase", "Flow Direction :"))
        self.btnOpenDialog.setText(_translate("CatchmentDialogBase", "...."))
        self.btnCancel.setText(_translate("CatchmentDialogBase", "Cancel"))
        self.btnOK.setText(_translate("CatchmentDialogBase", "OK"))
        self.label_3.setText(_translate("CatchmentDialogBase", "Flow Accumulation :"))
        self.label_4.setText(_translate("CatchmentDialogBase", "Stream :"))
        self.label_5.setText(_translate("CatchmentDialogBase", "Output :"))
