# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Drainage_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrainageDockWidgetBase(object):
    def setupUi(self, DrainageDockWidgetBase):
        DrainageDockWidgetBase.setObjectName("DrainageDockWidgetBase")
        DrainageDockWidgetBase.resize(373, 449)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        DrainageDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(DrainageDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(DrainageDockWidgetBase)

    def retranslateUi(self, DrainageDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        DrainageDockWidgetBase.setWindowTitle(_translate("DrainageDockWidgetBase", "Drainage"))
