# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drainage_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrainageDialogBase(object):
    def setupUi(self, DrainageDialogBase):
        DrainageDialogBase.setObjectName("DrainageDialogBase")
        DrainageDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(DrainageDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(DrainageDialogBase)
        self.button_box.accepted.connect(DrainageDialogBase.accept)
        self.button_box.rejected.connect(DrainageDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(DrainageDialogBase)

    def retranslateUi(self, DrainageDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DrainageDialogBase.setWindowTitle(_translate("DrainageDialogBase", "Drainage"))
