# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FillSink_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FillSinkDialogBase(object):
    def setupUi(self, FillSinkDialogBase):
        FillSinkDialogBase.setObjectName("FillSinkDialogBase")
        FillSinkDialogBase.resize(507, 199)
        self.btnOK = QtWidgets.QPushButton(FillSinkDialogBase)
        self.btnOK.setGeometry(QtCore.QRect(310, 150, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.txtOutput = QtWidgets.QLineEdit(FillSinkDialogBase)
        self.txtOutput.setGeometry(QtCore.QRect(130, 110, 261, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.label = QtWidgets.QLabel(FillSinkDialogBase)
        self.label.setGeometry(QtCore.QRect(24, 35, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FillSinkDialogBase)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 81, 16))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.cmbLayers = QtWidgets.QComboBox(FillSinkDialogBase)
        self.cmbLayers.setGeometry(QtCore.QRect(130, 30, 341, 22))
        self.cmbLayers.setObjectName("cmbLayers")
        self.btnOpenDialog = QtWidgets.QPushButton(FillSinkDialogBase)
        self.btnOpenDialog.setGeometry(QtCore.QRect(400, 110, 75, 23))
        self.btnOpenDialog.setObjectName("btnOpenDialog")
        self.btnCancel = QtWidgets.QPushButton(FillSinkDialogBase)
        self.btnCancel.setGeometry(QtCore.QRect(400, 150, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.label_3 = QtWidgets.QLabel(FillSinkDialogBase)
        self.label_3.setGeometry(QtCore.QRect(34, 70, 80, 12))
        self.label_3.setObjectName("label_3")
        self.cmbShape = QtWidgets.QComboBox(FillSinkDialogBase)
        self.cmbShape.setGeometry(QtCore.QRect(130, 70, 341, 22))
        self.cmbShape.setObjectName("cmbShape")

        self.retranslateUi(FillSinkDialogBase)
        QtCore.QMetaObject.connectSlotsByName(FillSinkDialogBase)

    def retranslateUi(self, FillSinkDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FillSinkDialogBase.setWindowTitle(_translate("FillSinkDialogBase", "FillSink"))
        self.btnOK.setText(_translate("FillSinkDialogBase", "OK"))
        self.label.setText(_translate("FillSinkDialogBase", "Elevation Grid :"))
        self.label_2.setText(_translate("FillSinkDialogBase", "Output Grid :"))
        self.btnOpenDialog.setText(_translate("FillSinkDialogBase", "...."))
        self.btnCancel.setText(_translate("FillSinkDialogBase", "Cancel"))
        self.label_3.setText(_translate("FillSinkDialogBase", "Point Shape :"))
