# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flat_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlatDialogBase(object):
    def setupUi(self, FlatDialogBase):
        FlatDialogBase.setObjectName("FlatDialogBase")
        FlatDialogBase.resize(506, 139)
        FlatDialogBase.setSizeGripEnabled(False)
        self.label = QtWidgets.QLabel(FlatDialogBase)
        self.label.setGeometry(QtCore.QRect(34, 25, 91, 16))
        self.label.setObjectName("label")
        self.btnCancel = QtWidgets.QPushButton(FlatDialogBase)
        self.btnCancel.setGeometry(QtCore.QRect(410, 100, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOpenDialog = QtWidgets.QPushButton(FlatDialogBase)
        self.btnOpenDialog.setGeometry(QtCore.QRect(410, 60, 75, 23))
        self.btnOpenDialog.setObjectName("btnOpenDialog")
        self.btnOK = QtWidgets.QPushButton(FlatDialogBase)
        self.btnOK.setGeometry(QtCore.QRect(320, 100, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.txtOutput = QtWidgets.QLineEdit(FlatDialogBase)
        self.txtOutput.setGeometry(QtCore.QRect(140, 60, 261, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.cmbLayers = QtWidgets.QComboBox(FlatDialogBase)
        self.cmbLayers.setGeometry(QtCore.QRect(140, 20, 341, 22))
        self.cmbLayers.setObjectName("cmbLayers")
        self.label_2 = QtWidgets.QLabel(FlatDialogBase)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(FlatDialogBase)
        QtCore.QMetaObject.connectSlotsByName(FlatDialogBase)

    def retranslateUi(self, FlatDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FlatDialogBase.setWindowTitle(_translate("FlatDialogBase", "Flat"))
        self.label.setText(_translate("FlatDialogBase", "Elevation Grid :"))
        self.btnCancel.setText(_translate("FlatDialogBase", "Cancel"))
        self.btnOpenDialog.setText(_translate("FlatDialogBase", "...."))
        self.btnOK.setText(_translate("FlatDialogBase", "OK"))
        self.label_2.setText(_translate("FlatDialogBase", "Output Grid :"))
