# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flow_Accumulation_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Flow_AccumulationDialogBase(object):
    def setupUi(self, Flow_AccumulationDialogBase):
        Flow_AccumulationDialogBase.setObjectName("Flow_AccumulationDialogBase")
        Flow_AccumulationDialogBase.resize(506, 170)
        self.btnCancel = QtWidgets.QPushButton(Flow_AccumulationDialogBase)
        self.btnCancel.setGeometry(QtCore.QRect(416, 130, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.label = QtWidgets.QLabel(Flow_AccumulationDialogBase)
        self.label.setGeometry(QtCore.QRect(14, 25, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Flow_AccumulationDialogBase)
        self.label_2.setGeometry(QtCore.QRect(17, 60, 81, 16))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.cmbLayers = QtWidgets.QComboBox(Flow_AccumulationDialogBase)
        self.cmbLayers.setGeometry(QtCore.QRect(147, 20, 341, 22))
        self.cmbLayers.setObjectName("cmbLayers")
        self.btnOK = QtWidgets.QPushButton(Flow_AccumulationDialogBase)
        self.btnOK.setGeometry(QtCore.QRect(326, 130, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.txtOutput = QtWidgets.QLineEdit(Flow_AccumulationDialogBase)
        self.txtOutput.setGeometry(QtCore.QRect(147, 60, 261, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.btnOpenDialog = QtWidgets.QPushButton(Flow_AccumulationDialogBase)
        self.btnOpenDialog.setGeometry(QtCore.QRect(417, 60, 75, 23))
        self.btnOpenDialog.setObjectName("btnOpenDialog")
        self.chkEdge = QtWidgets.QCheckBox(Flow_AccumulationDialogBase)
        self.chkEdge.setGeometry(QtCore.QRect(147, 90, 181, 20))
        self.chkEdge.setObjectName("chkEdge")

        self.retranslateUi(Flow_AccumulationDialogBase)
        QtCore.QMetaObject.connectSlotsByName(Flow_AccumulationDialogBase)

    def retranslateUi(self, Flow_AccumulationDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Flow_AccumulationDialogBase.setWindowTitle(_translate("Flow_AccumulationDialogBase", "Flow Accumulation"))
        self.btnCancel.setText(_translate("Flow_AccumulationDialogBase", "Cancel"))
        self.label.setText(_translate("Flow_AccumulationDialogBase", "Flow Direction GRID :"))
        self.label_2.setText(_translate("Flow_AccumulationDialogBase", "Output Grid :"))
        self.btnOK.setText(_translate("Flow_AccumulationDialogBase", "OK"))
        self.btnOpenDialog.setText(_translate("Flow_AccumulationDialogBase", "...."))
        self.chkEdge.setText(_translate("Flow_AccumulationDialogBase", "Check Edge Contamination"))
