# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flow_Direction_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Flow_DirectionDialogBase(object):
    def setupUi(self, Flow_DirectionDialogBase):
        Flow_DirectionDialogBase.setObjectName("Flow_DirectionDialogBase")
        Flow_DirectionDialogBase.resize(507, 136)
        self.label = QtWidgets.QLabel(Flow_DirectionDialogBase)
        self.label.setGeometry(QtCore.QRect(14, 25, 91, 16))
        self.label.setObjectName("label")
        self.txtOutput = QtWidgets.QLineEdit(Flow_DirectionDialogBase)
        self.txtOutput.setGeometry(QtCore.QRect(120, 60, 261, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.label_2 = QtWidgets.QLabel(Flow_DirectionDialogBase)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.cmbLayers = QtWidgets.QComboBox(Flow_DirectionDialogBase)
        self.cmbLayers.setGeometry(QtCore.QRect(120, 20, 341, 22))
        self.cmbLayers.setObjectName("cmbLayers")
        self.btnCancel = QtWidgets.QPushButton(Flow_DirectionDialogBase)
        self.btnCancel.setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(Flow_DirectionDialogBase)
        self.btnOK.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.btnOpenDialog = QtWidgets.QPushButton(Flow_DirectionDialogBase)
        self.btnOpenDialog.setGeometry(QtCore.QRect(390, 60, 75, 23))
        self.btnOpenDialog.setObjectName("btnOpenDialog")

        self.retranslateUi(Flow_DirectionDialogBase)
        QtCore.QMetaObject.connectSlotsByName(Flow_DirectionDialogBase)

    def retranslateUi(self, Flow_DirectionDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Flow_DirectionDialogBase.setWindowTitle(_translate("Flow_DirectionDialogBase", "Flow Direction"))
        self.label.setText(_translate("Flow_DirectionDialogBase", "Fill Sink GRID :"))
        self.label_2.setText(_translate("Flow_DirectionDialogBase", "Output Grid :"))
        self.btnCancel.setText(_translate("Flow_DirectionDialogBase", "Cancel"))
        self.btnOK.setText(_translate("Flow_DirectionDialogBase", "OK"))
        self.btnOpenDialog.setText(_translate("Flow_DirectionDialogBase", "...."))
